version: '3.7'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://db:1433;databaseName=keycloak2;encrypt=true;trustServerCertificate=true
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: 123456@Aa

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on: [db]
    ports:
      - 8080:8080

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: keycloakdb
    user: root
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456@Aa
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=keycloak2
    ports:
      - 1434:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 123456@Aa -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s


volumes:
  mssql_data: